version: 0.2

phases:
  pre_build:
    commands:
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter doctor
      - flutter pub get
  build:
    commands:
      - flutter build web
  
artifacts:
  files:
    - '**/*'
  base-directory: build/web
