version: 0.2

phases:
  pre_build:
    commands:
      - flutter pub get
  build:
    commands:
      - flutter build web
  
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
